02-26 15:39:21 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-172]
02-26 15:40:17 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "PLANO_DE_CURSO[*] SELECT * FROM CADEIRA"; expected "PREPARE, {"; SQL statement:
PLANO_DE_CURSO SELECT * FROM CADEIRA [42001-172]
02-26 15:52:35 jdbc[36]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ID"; expected "INSERT, {"; SQL statement:
ID [42001-172]
02-26 15:57:50 jdbc[40]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "CADEIRA_ID"; SQL statement:
create table cadeira_cadeira (
cadeira_id                     integer not null,
cadeira_id                     integer not null,
constraint pk_cadeira_cadeira primary key (cadeira_id, cadeira_id)) [42121-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:383)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:560)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:135)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at com.jolbox.bonecp.StatementHandle.execute(StatementHandle.java:254)
	at play.api.db.evolutions.Evolutions$.play$api$db$evolutions$Evolutions$$execute(Evolutions.scala:121)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:261)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:261)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:261)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:257)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:257)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:471)
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110)
	at scala.util.Success.flatMap(Try.scala:200)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
02-26 16:23:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DIFICULDADE"; expected "DELETE, DROP, DECLARE, DEALLOCATE, {"; SQL statement:
DIFICULDADE [42001-172]
02-26 16:23:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "NOME"; SQL statement:
NOME [42000-172]
02-26 17:22:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "PLANO_DE_CURSO[*] SELECT * FROM CADEIRA"; expected "PREPARE, {"; SQL statement:
PLANO_DE_CURSO SELECT * FROM CADEIRA [42001-172]
02-26 23:08:25 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "PLANO_DE_CURSO[*] SELECT * FROM CADEIRA"; expected "PREPARE, {"; SQL statement:
PLANO_DE_CURSO SELECT * FROM CADEIRA [42001-172]
02-26 23:39:47 jdbc[8]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:655)
	at org.h2.server.web.WebApp.login(WebApp.java:900)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 14 more
02-26 23:39:47 jdbc[8]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:655)
	at org.h2.server.web.WebApp.login(WebApp.java:900)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 14 more
02-26 23:39:47 jdbc[8]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:655)
	at org.h2.server.web.WebApp.login(WebApp.java:900)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 14 more
02-27 00:13:08 jdbc[12]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:655)
	at org.h2.server.web.WebApp.login(WebApp.java:900)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110)
	at scala.util.Success.flatMap(Try.scala:200)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 43 more
02-27 00:13:08 jdbc[12]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110)
	at scala.util.Success.flatMap(Try.scala:200)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 43 more
02-27 00:13:08 jdbc[12]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:351)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110)
	at scala.util.Success.flatMap(Try.scala:200)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 43 more
02-27 00:13:11 jdbc[15]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "CADEIRAS_DO_CURSO_ID"; SQL statement:
create table Cadeiras_do_Curso_Cadeiras_do_Cu (
Cadeiras_do_Curso_id           bigint not null,
Cadeiras_do_Curso_id           bigint not null,
constraint pk_Cadeiras_do_Curso_Cadeiras_do_Cu primary key (Cadeiras_do_Curso_id, Cadeiras_do_Curso_id)) [42121-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:383)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:560)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:135)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at com.jolbox.bonecp.StatementHandle.execute(StatementHandle.java:254)
	at play.api.db.evolutions.Evolutions$.play$api$db$evolutions$Evolutions$$execute(Evolutions.scala:121)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:261)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:261)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:261)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:257)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:257)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:471)
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110)
	at scala.util.Success.flatMap(Try.scala:200)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
02-27 00:13:25 jdbc[23]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION[*] SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval [42001-172]
02-27 00:34:00 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION[*] SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL UNION SELECT PLANO_DE_CURSO_SEQ.NEXTVAL "; expected "identifier"; SQL statement:
select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval union select plano_de_curso_seq.nextval [42001-172]
02-27 01:05:08 jdbc[26]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:655)
	at org.h2.server.web.WebApp.login(WebApp.java:900)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 14 more
02-27 01:07:00 jdbc[30]: exception
org.h2.jdbc.JdbcSQLException: Duplicate column name "CADEIRAS_DO_CURSO_ID"; SQL statement:
create table Cadeiras_do_Curso_Cadeiras_do_Cu (
Cadeiras_do_Curso_id           bigint not null,
Cadeiras_do_Curso_id           bigint not null,
constraint pk_Cadeiras_do_Curso_Cadeiras_do_Cu primary key (Cadeiras_do_Curso_id, Cadeiras_do_Curso_id)) [42121-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.setColumns(Table.java:383)
	at org.h2.table.TableBase.<init>(TableBase.java:35)
	at org.h2.table.RegularTable.<init>(RegularTable.java:74)
	at org.h2.schema.Schema.createTable(Schema.java:560)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:135)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:180)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at com.jolbox.bonecp.StatementHandle.execute(StatementHandle.java:254)
	at play.api.db.evolutions.Evolutions$.play$api$db$evolutions$Evolutions$$execute(Evolutions.scala:121)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:261)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:261)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:261)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:257)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:257)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:471)
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.Play$.start(Play.scala:87)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112)
	at scala.Option.map(Option.scala:145)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112)
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110)
	at scala.util.Success.flatMap(Try.scala:200)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110)
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
